# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(433, 293)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 70, 47, 13))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 120, 47, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 190, 47, 13))
        self.label_4.setObjectName("label_4")
        self.confirm_button = QtWidgets.QPushButton(Dialog)
        self.confirm_button.setGeometry(QtCore.QRect(310, 240, 111, 31))
        self.confirm_button.setObjectName("confirm_button")
        self.line_barkod = QtWidgets.QLineEdit(Dialog)
        self.line_barkod.setGeometry(QtCore.QRect(70, 60, 351, 31))
        self.line_barkod.setObjectName("line_barkod")
        self.line_part = QtWidgets.QLineEdit(Dialog)
        self.line_part.setGeometry(QtCore.QRect(70, 120, 351, 31))
        self.line_part.setObjectName("line_part")
        self.line_guild = QtWidgets.QLineEdit(Dialog)
        self.line_guild.setGeometry(QtCore.QRect(70, 180, 351, 31))
        self.line_guild.setObjectName("line_guild")
        self.status = QtWidgets.QProgressBar(Dialog)
        self.status.setGeometry(QtCore.QRect(150, 20, 171, 20))
        self.status.setProperty("value", 24)
        self.status.setObjectName("status")
        self.synch_button = QtWidgets.QPushButton(Dialog)
        self.synch_button.setGeometry(QtCore.QRect(40, 20, 101, 23))
        self.synch_button.setObjectName("synch_button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Баркод"))
        self.label_3.setText(_translate("Dialog", "Партия"))
        self.label_4.setText(_translate("Dialog", "Цех"))
        self.confirm_button.setText(_translate("Dialog", "Принт"))
        self.synch_button.setText(_translate("Dialog", "Синхронизация"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
